language: python
python:
 - "2.7"
 - "3.3"
 - "3.4"
 - "3.5"
 - "pypy"
 - "pypy3"
install:
 - pip install --upgrade pip
 - "if [[ $TRAVIS_PYTHON_VERSION != 'pypy'* ]]; then pip install pylzma; fi"
 - "pip install .[http,s3,streaming,tests]"
script: "nosetests -vv"
notifications:
  webhooks: https://readthedocs.org/build/pysparkling
